/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-07-19 13:50:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Arrays;
import hyphen.entity.Appointment;
import hyphen.dao.AppointmentDAO;
import hyphen.entity.Doctor;
import java.util.List;
import hyphen.dao.DoctorDao;
import hyphen.conn.DBConnect;
import java.sql.Connection;

public final class edit_005fview_005fappointment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/header_link.jsp", Long.valueOf(1689656687043L));
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1689656665983L));
    _jspx_dependants.put("jar:file:/home/hyphen/Documents/Javahyphen/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/12-Maven-HospitalMGMT-Internal/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/footer_link.jsp", Long.valueOf(1689647789695L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1688798783080L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Arrays");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("hyphen.dao.AppointmentDAO");
    _jspx_imports_classes.add("hyphen.entity.Doctor");
    _jspx_imports_classes.add("hyphen.dao.DoctorDao");
    _jspx_imports_classes.add("hyphen.entity.Appointment");
    _jspx_imports_classes.add("hyphen.conn.DBConnect");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>User - Edit View Appointment</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\">\n");
      out.write("	\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".badge-btn {\n");
      out.write("	padding: 4px 6px;\n");
      out.write("	border: 1px solid #ddcccc;\n");
      out.write("	display: flex;\n");
      out.write("	border-radius: 4px;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body class=\"bg-light\">\n");
      out.write("	");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light\"\n");
      out.write("	style=\"background-color: #e3f2fd;\">\n");
      out.write("	<a class=\"navbar-brand\" href=\"#\"> <i class=\"fa fa-home\"></i> Hospital MGMT</a>\n");
      out.write("	<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("		data-target=\"#navbarNav\" aria-controls=\"navbarNav\"\n");
      out.write("		aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("		<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("	</button>\n");
      out.write("	<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n");
      out.write("		<ul class=\"navbar-nav ml-auto mb-2 mb-lg-0\"> \n");
      out.write("		\n");
      out.write("			<li class=\"nav-item\">\n");
      out.write("				<a class=\"nav-link\" href=\"gallery.jsp\">Gallery</a>\n");
      out.write("			</li>			\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("	\n");
      out.write("				\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("			\n");
      out.write("										\n");
      out.write("\n");
      out.write("		</ul>	\n");
      out.write("		\n");
      out.write("	</div>\n");
      out.write("</nav>");
      out.write("\n");
      out.write("	\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("		\n");
      out.write("	<div class=\"container pt-2 mb-5\"> \n");
      out.write("\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("		<header class=\"header mb-5\">\n");
      out.write("			<h1 id=\"title\" class=\"text-center\">Take Appointment</h1>\n");
      out.write("			<p id=\"description\" class=\"text-center\">Thank you for Appointment, we will connect you shortly</p>\n");
      out.write("		</header>\n");
      out.write("		\n");
      out.write("		<div class=\"custom-form\">\n");
      out.write("			<div class=\"form-wrap\">\n");
      out.write("			\n");
      out.write("			");

				int id = Integer.parseInt(request.getParameter("id"));
				AppointmentDAO apponDao = new AppointmentDAO(DBConnect.getConnection());
				Appointment appon = apponDao.getAllAppointmentByApponID(id, "appointment");
			
      out.write("\n");
      out.write("			\n");
      out.write("				<form id=\"take-appontment\" action=\"edit_user_appointment\" method=\"POST\">\n");
      out.write("					\n");
      out.write("					<input type=\"hidden\" name=\"userId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userObj.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("					<div class=\"row\">	\n");
      out.write("						<div class=\"col-md-6\">\n");
      out.write("							<div class=\"form-group\">\n");
      out.write("								<label for=\"name\">Full Name</label>\n");
      out.write("								<input type=\"text\" name=\"name\" id=\"name\" value=\"");
      out.print( appon.getName() );
      out.write("\" placeholder=\"Enter your name\" class=\"form-control\" required>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"col-md-6\">\n");
      out.write("							<div class=\"form-group\">\n");
      out.write("								<label for=\"gender\">Gender</label>\n");
      out.write("								<select id=\"gender\" name=\"gender\" class=\"form-control\" required>\n");
      out.write("								");

									String[] genderArr = {"Male", "Female", "Other"};
								
      out.write("\n");
      out.write("									<option disabled selected>Select</option>\n");
      out.write("								");

									for(String gender : genderArr) {
								
      out.write("\n");
      out.write("									<option value=\"");
      out.print( gender );
      out.write('"');
      out.write(' ');
 
										if(gender.equals(appon.getGender())) {
									
      out.write(" selected\n");
      out.write("									");

										}
									
      out.write(">\n");
      out.write("									");
      out.print( gender );
      out.write("</option>\n");
      out.write("								");

									}
								
      out.write("\n");
      out.write("								</select>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("	\n");
      out.write("					<div class=\"row\">\n");
      out.write("						<div class=\"col-md-6\">\n");
      out.write("							<div class=\"form-group\">\n");
      out.write("								<label for=\"age\">Age </label>\n");
      out.write("								<input type=\"text\" name=\"age\" id=\"age\" value=\"");
      out.print( appon.getAge() );
      out.write("\" min=\"10\" max=\"99\" class=\"form-control\" placeholder=\"Age\">\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"col-md-6\">\n");
      out.write("							<div class=\"form-group\">\n");
      out.write("								<label for=\"appon_date\">Appointment Date\n");
      out.write("								<input type=\"date\" name=\"appon_date\" id=\"appon_date\" value=\"");
      out.print( appon.getAppon_date() );
      out.write("\" class=\"form-control\">\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("	\n");
      out.write("					<div class=\"row\">\n");
      out.write("						<div class=\"col-md-6\">\n");
      out.write("							<div class=\"form-group\">\n");
      out.write("								<label for=\"email\">Email\n");
      out.write("								<input type=\"email\" name=\"email\" id=\"email\" value=\"");
      out.print( appon.getEmail() );
      out.write("\" class=\"form-control\" placeholder=\"Enter Email\">\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"col-md-6\">\n");
      out.write("							<div class=\"form-group\">\n");
      out.write("								<label for=\"mobno\">Phone Number\n");
      out.write("								<input type=\"text\" name=\"mobno\" id=\"mobno\" value=\"");
      out.print( appon.getMobno() );
      out.write("\" class=\"form-control\" placeholder=\"Enter phone number\">\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("					<div class=\"row\">\n");
      out.write("						<div class=\"col-md-6\">\n");
      out.write("							<div class=\"form-group\">\n");
      out.write("								<label for=\"disease\">Diseases\n");
      out.write("								<input type=\"text\" name=\"disease\" id=\"disease\" value=\"");
      out.print( appon.getDisease() );
      out.write("\" class=\"form-control\" placeholder=\"Enter type of disease\">\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"col-md-6\">\n");
      out.write("							<div class=\"form-group\">\n");
      out.write("								<label for=\"doc_id\">Doctor</label>\n");
      out.write("								<select name=\"doc_id\" id=\"doc_id\" class=\"form-control\" required>\n");
      out.write("									<option disabled selected value>Select</option>\n");
      out.write("									");

										DoctorDao dao = new DoctorDao(DBConnect.getConnection());
										List<Doctor> docList = dao.getAllDoctors();
										
										for(Doctor doc : docList) {
									
      out.write("\n");
      out.write("										<option value=\"");
      out.print( doc.getDoc_id() );
      out.write("\"\n");
      out.write("											");
 if(doc.getDoc_id() == appon.getDoc_id()) { 
      out.write("\n");
      out.write("												selected\n");
      out.write("											");
 } 
      out.write("\n");
      out.write("										>\n");
      out.write("										\n");
      out.write("										");
      out.print( doc.getName() );
      out.write(' ');
      out.write('(');
      out.print( doc.getSpecialist() );
      out.write(")</option>\n");
      out.write("									");

										}
									
      out.write("	\n");
      out.write("									\n");
      out.write("								</select>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>		\n");
      out.write("					\n");
      out.write("					<div class=\"row\">\n");
      out.write("						<div class=\"col-md-6\">\n");
      out.write("							<div class=\"form-group\">\n");
      out.write("								<label>Would you recommend survey to a friend?</label>\n");
      out.write("								<div class=\"custom-control custom-radio custom-control-inline\">\n");
      out.write("									<input type=\"radio\" id=\"definitely\" value=\"Definitely\" name=\"survey_recom\" class=\"custom-control-input\"\n");
      out.write("										");
 if(appon.getSurvey_recom().equals("Definitely")) { 
      out.write("\n");
      out.write("											checked\n");
      out.write("										");
 } 
      out.write("\n");
      out.write("									>\n");
      out.write("									<label class=\"custom-control-label\" for=\"definitely\">Definitely</label>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"custom-control custom-radio custom-control-inline\">\n");
      out.write("									<input type=\"radio\" id=\"maybe\" value=\"Maybe\" name=\"survey_recom\" class=\"custom-control-input\"\n");
      out.write("										");
 if(appon.getSurvey_recom().equals("Maybe")) { 
      out.write("\n");
      out.write("											checked\n");
      out.write("										");
 } 
      out.write("									\n");
      out.write("									>\n");
      out.write("									<label class=\"custom-control-label\" for=\"maybe\">Maybe</label>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"custom-control custom-radio custom-control-inline\">\n");
      out.write("									<input type=\"radio\" id=\"not_sure\" value=\"Not sure\" name=\"survey_recom\" class=\"custom-control-input\"\n");
      out.write("										");
 if(appon.getSurvey_recom().equals("Not sure")) { 
      out.write("\n");
      out.write("											checked\n");
      out.write("										");
 } 
      out.write("									\n");
      out.write("									>\n");
      out.write("									<label class=\"custom-control-label\" for=\"not_sure\">Not\n");
      out.write("										sure</label>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("	\n");
      out.write("						<div class=\"col-md-6\">\n");
      out.write("							<div class=\"form-group\">\n");
      out.write("								<label>How you get this know about this hospital?</label>\n");
      out.write("								<div class=\"custom-control custom-checkbox custom-control-inline\">\n");
      out.write("									<input type=\"checkbox\" class=\"custom-control-input\" name=\"appon_info\" value=\"Friends\" id=\"by_friends\"\n");
      out.write("										");
 
											String frndInfo = appon.getAppon_info();
							      		  	String[] frndInfoArr = frndInfo.split(",");
								        	boolean frndCheck = Arrays.asList(frndInfoArr).contains("Friends");
											if(frndCheck) { 
      out.write("\n");
      out.write("												checked\n");
      out.write("										");
 	} 
      out.write("									\n");
      out.write("									>\n");
      out.write("									<label class=\"custom-control-label\" for=\"by_friends\">Friends</label>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"custom-control custom-checkbox custom-control-inline\">\n");
      out.write("									<input type=\"checkbox\" class=\"custom-control-input\" name=\"appon_info\" value=\"Relatives\" id=\"by_relatives\"\n");
      out.write("										");
 
											String reltvsInfo = appon.getAppon_info();
							      		  	String[] reltvsInfoArr = reltvsInfo.split(",");
								        	boolean reltvsCheck = Arrays.asList(reltvsInfoArr).contains("Relatives");
											if(reltvsCheck) { 
      out.write("\n");
      out.write("												checked\n");
      out.write("										");
 	} 
      out.write("									\n");
      out.write("									>\n");
      out.write("									<label class=\"custom-control-label\" for=\"by_relatives\">Relatives</label>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"custom-control custom-checkbox custom-control-inline\">\n");
      out.write("									<input type=\"checkbox\" class=\"custom-control-input\" name=\"appon_info\" value=\"Online\" id=\"by_online\"\n");
      out.write("										");
 
											String onlineInfo = appon.getAppon_info();
							      		  	String[] onlineInfoArr = onlineInfo.split(",");
								        	boolean onlineCheck = Arrays.asList(onlineInfoArr).contains("Online");
											if(onlineCheck) { 
      out.write("\n");
      out.write("												checked\n");
      out.write("										");
 	} 
      out.write("									\n");
      out.write("									>\n");
      out.write("									<label class=\"custom-control-label\" for=\"by_online\">Online</label>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"custom-control custom-checkbox custom-control-inline\">\n");
      out.write("									<input type=\"checkbox\" class=\"custom-control-input\" name=\"appon_info\" value=\"Newspapers\" id=\"by_news\"\n");
      out.write("										");
 
											String newsInfo = appon.getAppon_info();
							      		  	String[] newsInfoArr = newsInfo.split(",");
								        	boolean newsCheck = Arrays.asList(newsInfoArr).contains("Newspapers");
											if(newsCheck) { 
      out.write("\n");
      out.write("												checked\n");
      out.write("										");
 	} 
      out.write("									\n");
      out.write("									>\n");
      out.write("									<label class=\"custom-control-label\" for=\"by_news\">Newspapers</label>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"custom-control custom-checkbox custom-control-inline\">\n");
      out.write("									<input type=\"checkbox\" class=\"custom-control-input\" name=\"appon_info\" value=\"Advertisements\" id=\"by_adds\"\n");
      out.write("										");
 
											String advInfo = appon.getAppon_info();
							      		  	String[] adInfoArr = advInfo.split(",");
								        	boolean adCheck = Arrays.asList(adInfoArr).contains("Advertisements");
											if(adCheck) { 
      out.write("\n");
      out.write("												checked\n");
      out.write("										");
 	} 
      out.write("									\n");
      out.write("									>\n");
      out.write("									<label class=\"custom-control-label\" for=\"by_adds\">Advertisements</label>\n");
      out.write("								</div>								\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						\n");
      out.write("					</div>	\n");
      out.write("					\n");
      out.write("					<div class=\"row\">\n");
      out.write("						<div class=\"col-md-6\">\n");
      out.write("							<div class=\"form-group\">\n");
      out.write("								<label for=\"email\">Address\n");
      out.write("								<input type=\"text\" name=\"address\" id=\"address\" value=\"");
      out.print( appon.getAddress() );
      out.write("\" class=\"form-control\" placeholder=\"Enter address\">\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>														\n");
      out.write("	\n");
      out.write("					<div class=\"row\">\n");
      out.write("						<div class=\"col-md-12\">\n");
      out.write("							<div class=\"form-group\">\n");
      out.write("								<label for=\"comments\">Leave Message <small class=\"text-muted\">(optional)</small> </label>\n");
      out.write("								<textarea id=\"comments\" class=\"form-control\" name=\"comments\"\n");
      out.write("									placeholder=\"Enter your comment here...\">");
      out.print( appon.getComments());
      out.write("</textarea>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("	\n");
      out.write("					<div class=\"row\">\n");
      out.write("						<div class=\"col-md-4\">\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("							\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("					<input type=\"hidden\" name=\"id\" value=\"");
      out.print( appon.getAppon_id() );
      out.write("\" />\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	");
      out.write("\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\"></script>\n");
      out.write("	\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.min.js\" ></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	$(\"#success-alert\").fadeTo(2000, 500).slideUp(500, function() {\n");
      out.write("		$(\"#success-alert\").slideUp(500);\n");
      out.write("	});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	$(\"#error-alert\").fadeTo(2000, 500).slideUp(500, function() {\n");
      out.write("		$(\"#error-alert\").slideUp(500);\n");
      out.write("	});\n");
      out.write("</script>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /navbar.jsp(19,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty userObj }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("				<li class=\"nav-item\">\n");
          out.write("					<a class=\"nav-link\" href=\"admin_login.jsp\">Admin</a>\n");
          out.write("				</li>\n");
          out.write("				<li class=\"nav-item\">\n");
          out.write("					<a class=\"nav-link\" href=\"doctor_login.jsp\">Doctor</a>\n");
          out.write("				</li>\n");
          out.write("				<li class=\"nav-item\">\n");
          out.write("					<a class=\"nav-link\" href=\"user_login.jsp\">User</a>\n");
          out.write("				</li>	\n");
          out.write("				\n");
          out.write("				<li class=\"nav-item\">\n");
          out.write("					<a class=\"nav-link\" href=\"user_appointment.jsp\">Appointment</a>\n");
          out.write("				</li>\n");
          out.write("							\n");
          out.write("							\n");
          out.write("				<li class=\"nav-item\">\n");
          out.write("					<a class=\"nav-link\" href=\"signup.jsp\"><i class=\"fa fa-sign-in\"></i> Signup</a>\n");
          out.write("				</li>\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /navbar.jsp(40,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ not empty userObj }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("		\n");
          out.write("				<li class=\"nav-item\">\n");
          out.write("					<a class=\"nav-link\" href=\"user_appointment.jsp\">Appointment</a>\n");
          out.write("				</li>\n");
          out.write("				<li class=\"nav-item\">\n");
          out.write("					<a class=\"nav-link\" href=\"view_appointment.jsp\">View Appointment</a>\n");
          out.write("				</li>\n");
          out.write("								\n");
          out.write("	            <li class=\"nav-item dropdown ml-auto\">\n");
          out.write("	                <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"><i class=\"fa fa-user-circle\"></i> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userObj.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\n");
          out.write("	                <div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"navbarDropdownMenuLink\">\n");
          out.write("	                    <a class=\"dropdown-item media-body mb-0 small lh-125 border-bottom border-gray\" href=\"change_password.jsp\"> <i class=\"fa fa-vcard\" style=\"font-size: 1rem;\"></i> Change password</a>\n");
          out.write("	                    <a class=\"dropdown-item\" href=\"user_logout\"><i class=\"fa fa-sign-out\"></i> Logout</a>\n");
          out.write("	                </div>\n");
          out.write("	            </li>					\n");
          out.write("				\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /edit_view_appointment.jsp(33,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty userObj}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\n');
          out.write('	');
          out.write('	');
          if (_jspx_meth_c_005fredirect_005f0(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fredirect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:redirect
    org.apache.taglibs.standard.tag.rt.core.RedirectTag _jspx_th_c_005fredirect_005f0 = (org.apache.taglibs.standard.tag.rt.core.RedirectTag) _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.RedirectTag.class);
    boolean _jspx_th_c_005fredirect_005f0_reused = false;
    try {
      _jspx_th_c_005fredirect_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fredirect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /edit_view_appointment.jsp(34,2) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fredirect_005f0.setUrl("user_login.jsp");
      int _jspx_eval_c_005fredirect_005f0 = _jspx_th_c_005fredirect_005f0.doStartTag();
      if (_jspx_th_c_005fredirect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_c_005fredirect_005f0);
      _jspx_th_c_005fredirect_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fredirect_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fredirect_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /edit_view_appointment.jsp(39,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty successMsg}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			<div\n");
          out.write("				style=\"z-index: 1; position: absolute; right: 0; margin-right: 5px;\">\n");
          out.write("				<div class=\"alert-div\" id=\"success-alert\" style=\"position: relative\">\n");
          out.write("					<div class=\"alert alert-success alert-dismissible fade show\"\n");
          out.write("						role=\"alert\">\n");
          out.write("						<strong>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${successMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</strong>\n");
          out.write("\n");
          out.write("						<hr>\n");
          out.write("						<p class=\"mb-0\">Close the message box by clicking X to right.</p>\n");
          out.write("\n");
          out.write("						<button type=\"button\" class=\"close\" data-dismiss=\"alert\"\n");
          out.write("							aria-label=\"Close\">\n");
          out.write("							<span aria-hidden=\"true\">&times;</span>\n");
          out.write("						</button>\n");
          out.write("					</div>\n");
          out.write("				</div>\n");
          out.write("			</div>\n");
          out.write("			");
          if (_jspx_meth_c_005fremove_005f0(_jspx_th_c_005fif_005f3, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f0_reused = false;
    try {
      _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /edit_view_appointment.jsp(57,3) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setVar("successMsg");
      int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
      if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
      _jspx_th_c_005fremove_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /edit_view_appointment.jsp(60,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty errorMsg}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			<div style=\"z-index: 1; position: absolute; right: 0;\">\n");
          out.write("				<div class=\"alert-div\" id=\"error-alert\">\n");
          out.write("					<div class=\"alert alert-danger alert-dismissible fade show\"\n");
          out.write("						role=\"alert\">\n");
          out.write("						<strong>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</strong>\n");
          out.write("\n");
          out.write("						<hr>\n");
          out.write("						<p class=\"mb-0\">Close the message box by clicking X to right.</p>\n");
          out.write("						<button type=\"button\" class=\"close\" data-dismiss=\"alert\"\n");
          out.write("							aria-label=\"Close\">\n");
          out.write("							<span aria-hidden=\"true\">&times;</span>\n");
          out.write("						</button>\n");
          out.write("					</div>\n");
          out.write("				</div>\n");
          out.write("			</div>\n");
          out.write("			");
          if (_jspx_meth_c_005fremove_005f1(_jspx_th_c_005fif_005f4, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f1 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f1_reused = false;
    try {
      _jspx_th_c_005fremove_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
      // /edit_view_appointment.jsp(76,3) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f1.setVar("errorMsg");
      int _jspx_eval_c_005fremove_005f1 = _jspx_th_c_005fremove_005f1.doStartTag();
      if (_jspx_th_c_005fremove_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.reuse(_jspx_th_c_005fremove_005f1);
      _jspx_th_c_005fremove_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /edit_view_appointment.jsp(316,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty userObj }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("								<a href=\"user_login.jsp\" style=\"text-decoration: none;\">\n");
          out.write("									<button type=\"submit\" id=\"submit\" class=\"btn btn-primary btn-block\">Update Appointment</button>\n");
          out.write("								</a>\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /edit_view_appointment.jsp(321,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty userObj }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("								<a href=\"index.jsp\" style=\"text-decoration: none;\">\n");
          out.write("									<button type=\"submit\" id=\"submit\" class=\"btn btn-primary btn-block\">Update Appointment</button>\n");
          out.write("								</a>\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }
}
